#!/usr/bin/python                                                             

import os, commands, sys
import random

numRuns = 30
runName = "self_nov"
runName = runName+'_'
PenaltyType = str(0)


scriptFileName = "launchScript.sh"


def printScriptFile(dir, x,r):
    scriptfile  = open(scriptFileName,'w',)
    scriptfile.write( "#!/bin/bash \n")
    scriptfile.write( "\n")
    scriptfile.write( "#Do not edit. File automatically generated by fit based slurm .py\n")
    scriptfile.write( "\n")
    
    scriptfile.write("#SBATCH --job-name=bipednovFB \n")
    scriptfile.write("#SBATCH --account=EvolvingAI \n")
    scriptfile.write("#SBATCH -o "+dir+"/out \n")
    scriptfile.write("#SBATCH -e "+dir+"/err \n")
    scriptfile.write("#SBATCH --mail-type=ALL \n")
    scriptfile.write("#SBATCH --mail-user=hmengist@uwyo.edu \n")
    scriptfile.write("#SBATCH --nodes=1 \n")   
    scriptfile.write("#SBATCH --ntasks-per-node=16 \n")
    scriptfile.write("#SBATCH --ntasks=16 \n")
    scriptfile.write("#SBATCH --cpus-per-task=1 \n")
    scriptfile.write("#SBATCH --time=35:00:00 \n")
  

    #scriptfile.write( "echo \"Changing to directory: \" $experimentDir\n")
    #scriptfile.write( "cd $experimentDir\n")
    scriptfile.write( "\n")
    scriptfile.write( "mpirun -np 16 ./biped_fdo --biped -s biped_mut.ne -n --sg bipedstartgenes -o "+dir+"/novFandB_"+str(x)+" -r "+str(r)+"\n")
    scriptfile.write( "\n")
    scriptfile.write( "echo \"Done with run\"\n")
    scriptfile.close()
    os.system("chmod +x " + scriptFileName)

#main starts here

print 'Starting a batch of runs called: ' + runName

#printScriptFile()



for i in range(0,numRuns):
    runNum = i
    pwd = commands.getoutput("pwd")
    runDirShort = pwd+"/novwithFandB/"+"novFbinB_" + str(runNum)

    if os.path.isdir(runDirShort):
        print runDirShort + " already exists. Abort!"
        sys.exit(3)
    command = "mkdir "  + runDirShort
    os.system(command)
    #pwd = commands.getoutput("pwd")
    #experimentDir = pwd + "/novmaze" + runDirShort
    experimentDir = runDirShort
    
    r=random.randint(0,1000000)
    printScriptFile(experimentDir,i,r)
    command = ("sbatch " + scriptFileName)
    #srun ="-A EvolvingAI -N 1 -n 1 -c 16 -t 48:00:00 -J evo_bhv"+str(i)+" -e "+experimentDir+"/err -o "+experimentDir+"/out"
    #command = " ./mazesim -f goal -s maze.ne -e -m hard_maze_list.txt -o "+experimentDir+"/evo_bhv_maze_"+str(i)+" -r "+str(r)+"\n"
    #command =("srun " + srun + command)
    print command

    os.system(command)   
  
